name: Build and release

on:
  workflow_dispatch:

env:
  RELEASE_VERSION: "2.2"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and release

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup local branches
        run: |
          for branch in budget latency throughput magisk; do
            git branch $branch origin/$branch
          done

      - name: Checkout magisk branch and build
        run: |
          git checkout magisk
          bash build.sh

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.RELEASE_VERSION }}-compact-orb" KTweak-MM-*.zip
